name: 🌥 Docker Push

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
    types: [closed]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Get Github tag
        id: meta
        run: |
          curl --silent "https://api.github.com/repos/SecuriWiser/nuclei/releases/latest" | jq -r .tag_name | xargs -I {} echo TAG={} >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Create and populate serviceAccount.json
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
        run: |
          touch v2/internal/firebase/serviceAccount.json
          echo $SERVICE_ACCOUNT >> v2/internal/firebase/serviceAccount.json
          echo "cat serviceAccount.json"
          cat v2/internal/firebase/serviceAccount.json
        shell: bash

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: securiwiser/nuclei:latest,securiwiser/nuclei:${{ steps.meta.outputs.TAG }}
